name: macalculator
version: 0.1.0
summary: Una calculadora desarrollada para MAC
description: Es una calculadora especializada para los estudiantes de la carrera de MAC

confinement: strict
base: core18
grade: stable

slots:
  dbus-macalculator: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.yael.macalculator # adjust accordingly to your app name and
    
apps:
  macalculator:
    command: macalculator
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-macalculator
parts:
  super-cool-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
